In [3]:
import tensorflow as tf
import numpy as np

In [12]:
# Zero Tensor
tensor_zero=tf.constant(4)
print(tensor_zero)

tf.Tensor(4, shape=(), dtype=int32)


In [13]:
tensor_one_d= tf.constant([1,2,3,4])
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [9]:
# one dimensional array
tf.random.set_seed(42)

print(tf.random.uniform(shape=[4,], maxval=5, dtype=tf.int32, seed=10, name="one diamensional array"))
print(tf.random.uniform(shape=[4,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[4,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[4,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([2 3 3 0], shape=(4,), dtype=int32)
tf.Tensor([1 0 1 3], shape=(4,), dtype=int32)
tf.Tensor([2 4 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 1 3 3], shape=(4,), dtype=int32)


In [17]:
# two dimensional array (combination of two one dimensional arrays)
print(tf.random.uniform(shape=[2,3], maxval=5, dtype=tf.int32, seed=10, name="two diamensional array"))


tf.Tensor(
[[0 1 3]
 [3 2 1]], shape=(2, 3), dtype=int32)


In [ ]:
two_d_array=tf.constant([
                            [1,2,3],
                            [4,5,6]
                        ])

print(two_d_array) # rows, cols

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# three dims tensor (combination of two or more than two dimensional arrays)
tesor_three_d = tf.constant(
[[
 [1,2,3],
[4,5,6]],
[
 [5,7,7],
[4,6,8]
]]
)
print(tesor_three_d) # rows, cols, depth

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[5 7 7]
  [4 6 8]]], shape=(2, 2, 3), dtype=int32)


In [19]:
print(tf.random.uniform(shape=[2,2,3], maxval=5, dtype=tf.int32, seed=10, name="two diamensional array"))

tf.Tensor(
[[[2 1 1]
  [0 0 1]]

 [[2 3 4]
  [2 0 1]]], shape=(2, 2, 3), dtype=int32)


In [20]:
# 4D array
tensor_4d = tf.constant([[[[1,2,3],[4,5,6]],[[5,7,7],[4,6,8]]]])
print(tensor_4d)

tf.Tensor(
[[[[1 2 3]
   [4 5 6]]

  [[5 7 7]
   [4 6 8]]]], shape=(1, 2, 2, 3), dtype=int32)


In [21]:
print(tf.random.uniform(shape=[2,2,2,2], maxval=5, dtype=tf.int32, seed=10, name="two diamensional array"))

tf.Tensor(
[[[[3 2]
   [1 3]]

  [[1 1]
   [0 2]]]


 [[[1 1]
   [0 4]]

  [[4 2]
   [0 0]]]], shape=(2, 2, 2, 2), dtype=int32)


In [24]:
tensor_4d= tf.random.uniform(shape=[2,2,2,4], maxval=100, dtype=tf.int32, seed=10)
print(tensor_4d)

tf.Tensor(
[[[[10 36 16 45]
   [70 65 41 89]]

  [[99 47 53 18]
   [81 41 75 40]]]


 [[[50 62 63 67]
   [98  9 11 78]]

  [[95 81 31 45]
   [45 10 93 61]]]], shape=(2, 2, 2, 4), dtype=int32)


In [33]:
# extract a single 16 45
tensor_4d[0][0][0][2:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([16, 45], dtype=int32)>

In [40]:
tensor_4d[0][0][:,2:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 45],
       [41, 89]], dtype=int32)>

## create similar tensor like (transformer)-> (batch_size, seq_len, dims)

In [41]:
# batch_size, seq_len, embedding_size (no of sentences, no of words, no of features)


In [60]:
transformer_embeddings = tf.random.normal(shape=[4,4,5], 
                 mean=0.0, 
                 dtype= tf.dtypes.float64, # full precision
                 seed=42
                 )

print(transformer_embeddings)


tf.Tensor(
[[[ 0.95075673 -2.28740708 -1.59376459  0.0245846  -0.33645878]
  [ 0.55803349 -0.10502974 -0.60914888  1.42606363 -0.56166456]
  [-0.27218109 -1.30801079 -0.08374611  1.81218988 -0.7071872 ]
  [-0.65792107  0.75420805 -0.52310244  0.14188419  0.5784366 ]]

 [[ 0.61086185 -1.29269257  0.67200247 -1.00161925  1.08985974]
  [-0.27384856  1.45300657 -1.22899333 -0.97913192 -1.77856091]
  [ 0.6611668   1.64197706  1.04852643  0.2012764  -0.04678045]
  [ 0.81292695 -2.11376328 -0.03419352 -1.51463478 -1.20972808]]

 [[-1.05230463 -0.95102975  0.32000211  2.23686846 -0.70733631]
  [-0.3560446   1.14503328  1.3267269  -0.12236576 -0.90324379]
  [ 0.05261829  1.28092332  0.6054792   0.53793594 -0.5644898 ]
  [ 0.26696764  0.53670286  0.09354302 -0.09567358 -0.84024325]]

 [[ 1.1585465  -2.25164507 -0.22689102 -0.19397162  0.4733954 ]
  [-0.43175785 -0.41418808  0.92615407 -1.41959332 -1.41033433]
  [-1.24787178  0.85035968  2.58178466  1.67031198  0.17116681]
  [-0.4014426   1.08351

In [61]:
# first token of first sentence
transformer_embeddings[0][0]

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 0.95075673, -2.28740708, -1.59376459,  0.0245846 , -0.33645878])>

In [64]:
print(transformer_embeddings)

tf.Tensor(
[[[ 0.95075673 -2.28740708 -1.59376459  0.0245846  -0.33645878]
  [ 0.55803349 -0.10502974 -0.60914888  1.42606363 -0.56166456]
  [-0.27218109 -1.30801079 -0.08374611  1.81218988 -0.7071872 ]
  [-0.65792107  0.75420805 -0.52310244  0.14188419  0.5784366 ]]

 [[ 0.61086185 -1.29269257  0.67200247 -1.00161925  1.08985974]
  [-0.27384856  1.45300657 -1.22899333 -0.97913192 -1.77856091]
  [ 0.6611668   1.64197706  1.04852643  0.2012764  -0.04678045]
  [ 0.81292695 -2.11376328 -0.03419352 -1.51463478 -1.20972808]]

 [[-1.05230463 -0.95102975  0.32000211  2.23686846 -0.70733631]
  [-0.3560446   1.14503328  1.3267269  -0.12236576 -0.90324379]
  [ 0.05261829  1.28092332  0.6054792   0.53793594 -0.5644898 ]
  [ 0.26696764  0.53670286  0.09354302 -0.09567358 -0.84024325]]

 [[ 1.1585465  -2.25164507 -0.22689102 -0.19397162  0.4733954 ]
  [-0.43175785 -0.41418808  0.92615407 -1.41959332 -1.41033433]
  [-1.24787178  0.85035968  2.58178466  1.67031198  0.17116681]
  [-0.4014426   1.08351

In [75]:
print(transformer_embeddings[:,:, 3:]) # select last 2 cols of each sentece and each tokens

tf.Tensor(
[[[ 0.0245846  -0.33645878]
  [ 1.42606363 -0.56166456]
  [ 1.81218988 -0.7071872 ]
  [ 0.14188419  0.5784366 ]]

 [[-1.00161925  1.08985974]
  [-0.97913192 -1.77856091]
  [ 0.2012764  -0.04678045]
  [-1.51463478 -1.20972808]]

 [[ 2.23686846 -0.70733631]
  [-0.12236576 -0.90324379]
  [ 0.53793594 -0.5644898 ]
  [-0.09567358 -0.84024325]]

 [[-0.19397162  0.4733954 ]
  [-1.41959332 -1.41033433]
  [ 1.67031198  0.17116681]
  [-0.43667598 -0.81694937]]], shape=(4, 4, 2), dtype=float64)


## Change data type (casting operation)

In [79]:
## convert to float16
tf.cast(transformer_embeddings, dtype=tf.float16) # convert to float16

<tf.Tensor: shape=(4, 4, 5), dtype=float16, numpy=
array([[[ 0.9507 , -2.287  , -1.594  ,  0.02458, -0.3364 ],
        [ 0.558  , -0.10504, -0.6094 ,  1.426  , -0.5615 ],
        [-0.2722 , -1.308  , -0.08374,  1.8125 , -0.707  ],
        [-0.6577 ,  0.7544 , -0.523  ,  0.1418 ,  0.5786 ]],

       [[ 0.611  , -1.293  ,  0.672  , -1.002  ,  1.09   ],
        [-0.274  ,  1.453  , -1.229  , -0.979  , -1.778  ],
        [ 0.661  ,  1.642  ,  1.049  ,  0.2013 , -0.04678],
        [ 0.813  , -2.113  , -0.03418, -1.515  , -1.21   ]],

       [[-1.053  , -0.951  ,  0.32   ,  2.236  , -0.7075 ],
        [-0.356  ,  1.1455 ,  1.327  , -0.1224 , -0.9033 ],
        [ 0.0526 ,  1.281  ,  0.6055 ,  0.538  , -0.5645 ],
        [ 0.2668 ,  0.5366 ,  0.09357, -0.0957 , -0.8403 ]],

       [[ 1.158  , -2.252  , -0.2269 , -0.194  ,  0.4734 ],
        [-0.4316 , -0.4143 ,  0.9263 , -1.42   , -1.41   ],
        [-1.248  ,  0.8506 ,  2.582  ,  1.67   ,  0.1711 ],
        [-0.4014 ,  1.084  ,  0.981  , -0.4

In [81]:
tf.cast(transformer_embeddings, dtype=tf.qint16)

<tf.Tensor: shape=(4, 4, 5), dtype=qint16, numpy=
array([[[ 0, -2, -1,  0,  0],
        [ 0,  0,  0,  1,  0],
        [ 0, -1,  0,  1,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0, -1,  0, -1,  1],
        [ 0,  1, -1,  0, -1],
        [ 0,  1,  1,  0,  0],
        [ 0, -2,  0, -1, -1]],

       [[-1,  0,  0,  2,  0],
        [ 0,  1,  1,  0,  0],
        [ 0,  1,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 1, -2,  0,  0,  0],
        [ 0,  0,  0, -1, -1],
        [-1,  0,  2,  1,  0],
        [ 0,  1,  0,  0,  0]]], dtype=int16)>

In [84]:
tensor_int32= tf.cast(transformer_embeddings, dtype=tf.qint32)
tensor_int32

<tf.Tensor: shape=(4, 4, 5), dtype=qint32, numpy=
array([[[ 0, -2, -1,  0,  0],
        [ 0,  0,  0,  1,  0],
        [ 0, -1,  0,  1,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0, -1,  0, -1,  1],
        [ 0,  1, -1,  0, -1],
        [ 0,  1,  1,  0,  0],
        [ 0, -2,  0, -1, -1]],

       [[-1,  0,  0,  2,  0],
        [ 0,  1,  1,  0,  0],
        [ 0,  1,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 1, -2,  0,  0,  0],
        [ 0,  0,  0, -1, -1],
        [-1,  0,  2,  1,  0],
        [ 0,  1,  0,  0,  0]]], dtype=int32)>

In [85]:
tf.cast(tensor_int32, dtype=tf.bool)

<tf.Tensor: shape=(4, 4, 5), dtype=bool, numpy=
array([[[False,  True,  True, False, False],
        [False, False, False,  True, False],
        [False,  True, False,  True, False],
        [False, False, False, False, False]],

       [[False,  True, False,  True,  True],
        [False,  True,  True, False,  True],
        [False,  True,  True, False, False],
        [False,  True, False,  True,  True]],

       [[ True, False, False,  True, False],
        [False,  True,  True, False, False],
        [False,  True, False, False, False],
        [False, False, False, False, False]],

       [[ True,  True, False, False, False],
        [False, False, False,  True,  True],
        [ True, False,  True,  True, False],
        [False,  True, False, False, False]]])>

# indentity matric

In [87]:
tf.eye(
    3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [89]:
import tensorflow as tf

# Example: Create a diagonal matrix
diagonal_elements = tf.constant([1, 2, 3])
diagonal_matrix = tf.linalg.diag(diagonal_elements)
diagonal_matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]], dtype=int32)>

In [92]:
tf.eye(
    5,
    num_columns=None,
    batch_shape=(2,4),
    dtype=tf.dtypes.float32,
    name=None
)

<tf.Tensor: shape=(2, 4, 5, 5), dtype=float32, numpy=
array([[[[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]],

        [[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]],

        [[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]],

        [[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]]],


       [[[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]],

        [[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]],

  

# fill

In [94]:
tf.fill(
    dims= (4,2), 
    value= 8, 
    name=None, 
    layout=None
)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[8, 8],
       [8, 8],
       [8, 8],
       [8, 8]], dtype=int32)>

In [96]:
elems = tf.constant([1, 2, 3, 4, 5, 6])
sum = tf.foldl(lambda a, x: a + x, elems)
# sum == 21
sum

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [98]:
## create a tensor of ones
tensor_ones = tf.ones(shape=[2, 3], dtype=tf.float32, name="ones_tensor")
tensor_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [99]:
tf.zeros(shape=[2, 3], dtype=tf.float32, name="zeros_tensor")

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

## Random tensorts

In [100]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[100.32747   99.15737 ]
 [100.319435  98.592445]
 [ 97.61194   98.960754]], shape=(3, 2), dtype=float32)


In [104]:
tf.random.uniform(shape=[4,4], minval=20, maxval=40, dtype= tf.int32, seed=10, name="random_tensor")

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[36, 38, 20, 24],
       [37, 20, 26, 22],
       [26, 39, 30, 38],
       [21, 32, 25, 20]], dtype=int32)>

In [101]:
# -Tensors are Multi Dimensional Arrays

## Argmax

In [105]:
array= tf.random.uniform(shape=[8,], minval=50, maxval=100, dtype=tf.int32, seed=10, name="random_tensor")
print(array)

tf.Tensor([85 72 54 65 65 93 66 58], shape=(8,), dtype=int32)


In [110]:
# Returns the index with the largest value across axes of a tensor.
max_num_index=tf.math.argmax(array, axis=0, output_type=tf.int32, name=None)
max_num_index # give at what position the max number is present in the array

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [109]:
array[max_num_index] # maximum number in the array

<tf.Tensor: shape=(), dtype=int32, numpy=93>

In [113]:
tf.argmax(array, axis=-1, output_type=tf.int32, name=None)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [134]:
array2= tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
array2

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 2, 20, 30,  3,  6],
       [ 3, 11, 16,  1,  8],
       [14, 45, 23,  5, 27]], dtype=int32)>

In [139]:
tf.argmax(array2, axis=0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>

In [140]:
tf.argmax(array2, axis=1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1])>

## argmax axis concept

    - Axis 0 goes down the columns (vertically).

    - Axis 1 goes across the rows (horizontally).

In [155]:
tensor = tf.constant([[1, 8, 3],
                        [4, 5, 6]])

result = tf.argmax(tensor, axis=0)
print(result)
## it will go across the columns and giving ans [1 0 1] (second row max, first row max, second row max)

tf.Tensor([1 0 1], shape=(3,), dtype=int64)


In [158]:
# axis =1 , It'll go by row
result2 = tf.argmax(tensor, axis=1)
print(result2) #row wise

tf.Tensor([1 2], shape=(2,), dtype=int64)


In [159]:
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 8, 3],
       [4, 5, 6]], dtype=int32)>

In [161]:
tf.transpose(tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [8, 5],
       [3, 6]], dtype=int32)>

In [163]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2],
                  [3,5],
                  [4,5]])

x_3 = tf.constant([[1,2,0,2],
                  [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)
# x_3.T = 4,2
# x_2.T = 2,3
# print(tf.transpose(x_3)@tf.transpose(x_2))
# tf.linalg.matmul(
#     x_3, x_2, transpose_a=True, transpose_b=True, adjoint_a=False, adjoint_b=True,
#     a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
# )

(1, 3) (3, 2) (2, 4) (2, 3)


In [164]:
x_1 =  tf.constant([[[1,2],
                    [3,5]],

                    [[10,0],
                    [1,2]],

                    [[5,0],
                    [2,0]]])

x_2 = tf.constant([[[5,1,4],
                    [34,15,1]],

                    [[1,2,2],
                    [5,3,2]],

                    [[2,2,3],
                    [1,1,1]]])

print(tf.linalg.matmul(x_1, x_2))

tf.Tensor(
[[[ 73  31   6]
  [185  78  17]]

 [[ 10  20  20]
  [ 11   8   6]]

 [[ 10  10  15]
  [  4   4   6]]], shape=(3, 2, 3), dtype=int32)


In [166]:
x_1.shape, x_2.shape

(TensorShape([3, 2, 2]), TensorShape([3, 2, 3]))

In [167]:
x_1 =  tf.constant([[0,0],
                    [0,2]])

x_2 = tf.constant([[1,0,0],
                    [0,0,0]])

print(tf.linalg.matmul(x_1, x_2))

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [168]:
x_1.shape, x_2.shape

(TensorShape([2, 2]), TensorShape([2, 3]))

In [169]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)

tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)

#### ( m-n <= lower) and ( n-m <= upper)
# m -- rows, n --- columns
tf.linalg.band_part(tensor_two_d, 0, -1)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [170]:
tensor_two_d

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  3.,   5., 100.],
       [  1.,   5.,   6.],
       [  2.,   3.,   8.]], dtype=float16)>

In [171]:
tf.linalg.band_part(tensor_two_d, 0, -1)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [173]:
tf.linalg.band_part(tensor_two_d, 0, 0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [ ]:
tf.linalg.band_part(tensor_two_d, 0, 0)